# Generated by Django 4.1 on 2024-12-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=models.TextField(verbose_name='Длинное описание'),
        ),
    ]
