# Generated by Django 4.1 on 2024-12-15 23:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
    ]
