# Generated by Django 4.0.6 on 2024-12-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
