# Generated by Django 4.0.6 on 2024-12-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-num'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
    ]
