# Generated by Django 4.0.6 on 2024-12-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(default=0, verbose_name='Длинное описание'),
            preserve_default=False,
        ),
    ]
