# Generated by Django 4.0.6 on 2024-12-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
