# Generated by Django 4.0.6 on 2024-12-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
